spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent_output = true

# This configures Spring Boot to trust and use forwarded headers (like X-Forwarded-For) when behind a proxy or load balancer
server.forward-headers-strategy=framework 

server.port=8080

# Filling these vars will population the `ApplicationConfiguration.java` automatically.
# See: `/src/main/java/com/adyen/workshop/configurations/ApplicationConfiguration.java`
apiKey=AQEuhmfxLo/JaBFDw0m/n3Q5qf3Veq59IaprW2ZZ03a/2JIbXXZ9Bd+lha8QKdXmuRDBXVsNvuR83LVYjEgiTGAH-Vz9pS2t4msLkP5c7XGh6v/Ahy7VqYNMC5AJf/46w/Aw=-i1ikjb2ULc3]u}ZRT(^
merchantAccount=REPLYAccount_SDPA_DEV_TEST
clientKey=test_LNPRPIBEZ5BIFAXBMTYL6XC2RMV3M6XP
hmac=D5C8071DF471228D736E3F82586045897EEFE6EB7085988D3DEC0DB117FC6811
